### ISSUE TITLE
Typst error: unexpected end of input, expecting new-line

### ISSUE THREAD

**Issue by ayoubelmhamdi** [jgm/typst-hs#12]
## Typst to markdown.
```bash
pandoc -s test.typ -o test.md
```
- test.typ:
```txt
he'*llo Worl*d
```
- error:
```log
"test.typ" (line 3, column 1):
unexpected end of input
expecting new-line, "*", "=", "//", "/*", "\\", "_", "$", "-", "+", digit, "/", "http://", "https://", "```", "`", "~", ".", "'", "\"", "<", "@", "#" or "["
```
or test.typ
```txt
l’*exactitude*.
```
### Explain the problem.
French has many single quotes`'`, the bug happened when we tried to convert strong typst text with beside quote.

### Pandoc version?
- `pandoc` v3.1.8
- Linux (void-linux compile from source)

**Comment by jgm** [comment]
Note that typst itself will raise an error for
```
he'*llo Worl*d
```
though it's okay with
```
he'*llo World*
```

**Comment by ayoubelmhamdi** [comment]
@jgm  the quoted `’` in `l’*exactitude*.` does not the default single-quoted. and typst accepted.

**Comment by jgm** [comment]
Oui, le problème dans `he'*llo Worl*d` n'est pas le `'`, mais les lettres après le dernier `*`.  Par exemple, typst n'accepte pas
```
l’*exactitude*x
```
<img width="796" alt="Screen Shot 2023-08-19 at 2 36 56 PM" src="https://github.com/jgm/typst-hs/assets/3044/61d9dec5-5397-4765-a65a-0f27c9fe01a7">

**Comment by ayoubelmhamdi** [comment]
`typst` accepte mon paragraphe, je pense parce que j'utilise le point après l'étoile.
```typst
La performance du modèle peut a été évaluée à partir de _la matrice de confusion_, qui permet
de calculer des métriques comme la *précision*, la *sensibilité (recall)* et le *F1-Score*, en plus
de l’*exactitude*. Ces mesures fournissent un aperçu plus large des performances du modèle, 
notamment quand il y a un déséquilibre des classes.
```
