### ISSUE TITLE
Typst to LaTeX: `dots` maps to `\cdots` when it should map to `\ldots`

### ISSUE THREAD

**Issue by MilesCranmer** [jgm/typst-hs#15]
**Explain the problem.**

File sketch.typ
```typ
$dots$
```

mapped to latex with:

```bash
> pandoc --to=latex sketch.typ -o sketch.tex
```

this results in
```tex
\(\cdots\)
```
when it should be `\ldots`.

**Pandoc version?**

3.1.8

**Comment by jgm** [comment]
OK, I think I've found the issue.
