### ISSUE TITLE
Pandoc error on multline string

### ISSUE THREAD

**Issue by ntjess** [jgm/typst-hs#20]
```typst
#let a = "
This is a
multiline string
"
```

This is a valid typst document but results in the following pandoc error:
```console
".\tmp.typ" (line 1, column 11):
unexpected "\n"
expecting "\"" or "\\"
```

**Comment by jgm** [comment]
Can you point to any typst documentation on multiline strings?

**Comment by ntjess** [comment]
Just looked quickly through docs, issues, and typst codebase tests. I can't seem to find any references to this behavior.

**Comment by laurmaedje** [comment]
There is no guarantee in the sense that breaking changes might occur, but it's public and intended behaviour.

**Comment by jgm** [comment]
Is there any special syntax?  Can you just put line breaks inside any string, or does the initial `"` need to be followed by a newline and the final `"` preceded by one?

**Comment by laurmaedje** [comment]
You can just put linebreaks anywhere.
