### ISSUE TITLE
Please consider replacing 'digits' library

### ISSUE THREAD

**Issue by iliastsi** [jgm/typst-hs#24]
Hi @jgm, happy new year!

`typst` depends on `digits`, which seems to be unmaintained (the last upload of `digits` was ~8 years ago, and the code repository doesn't exist anymore).

I noticed this since we are about to package `typst` for Debian, and we need to package `digits` as well. This is not a blocker, but I thought it would be good to let you now.

**Comment by jgm** [comment]
I've done this.
