### ISSUE TITLE
Incorrect LaTeX exponent syntax for Typst input in Pandoc conversion

### ISSUE THREAD

**Issue by vlashada** [jgm/typst-hs#29]
Explain the problem.
When converting typst to pandoc, I get that the typst code `$overline(a)$` is translated into `\(\underset{¯}{a}\)`, which does not seem to be correct

To reproduce:

echo "\$overline(a)\$" | pandoc -f typst -t latex

Pandoc version?
Pandoc 3.1.9

**Comment by jgm** [comment]
This has already been fixed (#9294).
But it's not yet in a released version. You can try a nightly.
