### ISSUE TITLE
Pandoc incorrectly resolves file path referenced by package

### ISSUE THREAD

**Issue by ntjess** [jgm/typst-hs#39]
```typst
#import "@preview/tada:0.1.0"
```

Converting this fails with
```console
pandoc: typst.toml: withBinaryFile: does not exist (No such file or directory)
```

This is because `tada` reads the version number from `typst.toml` that exists in its folder (https://github.com/typst/packages/blob/main/packages/preview/tada/0.1.0/lib.typ#L23). However, it appears pandoc is trying to read from the working directory, since placing a `typst.toml` file there resolves the warning. The solution is to ensure filepaths referenced by a package have their root resolve to the package directory.

**Comment by jgm** [comment]
I think it's fixed but more testing would be helpful.
