### ISSUE TITLE
Some inconsistencies with your parser vs the Rust parser

### ISSUE THREAD

**Issue by CMDJojo** [jgm/typst-hs#43]
Hi, me, @adelhult, and @leopoldwigbratt have been playing around a bit with typst-hs. We made a test suite parsing all packages in the [Typst package repository](https://github.com/typst/packages) to check for parser errors.

In total, there are about 1300 files, of which 76 failed. A few of them are actually invalid Typst, but most were problems with typst-hs. You can check out our test suite [here](https://github.com/adelhult/typst-hs-test-packages), but here is a summary:

## Trailing comment lines
It seems like ending a file with a comment line does not parse (unexpected EOF):
```typ
foo
// Hello
```
[example](https://github.com/adelhult/typst-hs-test-packages/blob/c91e781bcf5340fb1c9ecf5208f21ec181d78140/test/counter-examples/ending-comment.typ)

## Colon as part of label in argument treated as named argument
```typ
#let x = selector(<foo:bar>)
```
Typst treats this as a label named `foo:bar` while Typst-hs treats it like a named arg `<foo` (which is an invalid name and fails to parse)
[example](https://github.com/adelhult/typst-hs-test-packages/blob/1821b8ecc7624f4f579f4790cab0cbbe750c1ecb/test/counter-examples/colon_in_label_as_arg.typ)

## Raw literal in code mode is not supported
```typ 
#let x = `hello`
```
simply does not parse.
[example](https://github.com/adelhult/typst-hs-test-packages/blob/1821b8ecc7624f4f579f4790cab0cbbe750c1ecb/test/counter-examples/raw_in_code.typ)

## Space after math mode in lambda is not allowed
```typ
#let nada(ignore_me) = {
    "foo"
}
// removing space after $ works
#let w = nada(x => $x$ + x)
```
We encountered a strange bug where `$x$+x` works while `$x$ + x` doesn't.
[example](https://github.com/adelhult/typst-hs-test-packages/blob/1821b8ecc7624f4f579f4790cab0cbbe750c1ecb/test/counter-examples/space_after_math_mode.typ)

## NBSP/other spaces are not regarded Whitespace
In Typst, nbsp and hair space (and possibly many additional space characters) are regarded as whitespace, while in Typst-hs they are not.
[example](https://github.com/adelhult/typst-hs-test-packages/blob/1821b8ecc7624f4f579f4790cab0cbbe750c1ecb/test/counter-examples/nbsp.typ)

## Colon for declaring dict literal does not work with spreading
In Typst, you can write this:
```typ
#let d = (a: true, b: false)
#let nd = (: ..d)
```
`: ..d` is needed to first make `nd` of type `dictionary` before spreading the dictionary `d` into it, otherwise it will try to spread it as an array and fail. Typst-hs does not compile this.
[example](https://github.com/adelhult/typst-hs-test-packages/blob/1821b8ecc7624f4f579f4790cab0cbbe750c1ecb/test/counter-examples/spread_dict.typ)

These examples are reduced by hand out of some of the failures when testing on `typst/packages`, and there might be even smaller minimal examples. You can check out the log from running the tests [here](https://github.com/adelhult/typst-hs-test-packages/blob/1821b8ecc7624f4f579f4790cab0cbbe750c1ecb/errors.txt). Note that we found some files in the `typst/packages` repo does not parse with the rust implementation either, but our examples in the [counter-examples folder](https://github.com/adelhult/typst-hs-test-packages/tree/1821b8ecc7624f4f579f4790cab0cbbe750c1ecb/test/counter-examples) have been tested so they compile with the Rust implementation but not with typst-hs.

Hopefully we can contribute with fixing some of these bugs or adding some documentation!

**Comment by jgm** [comment]
Only 76 failures -- that's actually better than I would have expected!
Thanks for this summary.

- [ ] Trailing comment lines
- [ ] Colon as part of label in argument treated as named argument
- [ ] Raw literal in code mode is not supported
- [ ] Space after math mode in lambda is not allowed
- [ ] NBSP/other spaces are not regarded Whitespace
- [ ] Colon for declaring dict literal does not work with spreading

> Hopefully we can contribute with fixing some of these bugs or adding some documentation!

Do you know Haskell?  If so, it would be great to have more contributors on this project!  If there's a bug you want to work on, open an issue for it and assign yourself so we don't duplicate efforts. And let me know if anything is confusing about the code.

**Comment by CMDJojo** [comment]
Thank you for your reply! Nice work with the fixes. We are working on the dict literal in #45
