### ISSUE TITLE
Typst math mode ignored variables of some specific names

### ISSUE THREAD

**Issue by memset0** [jgm/typst-hs#51]
**Explain the problem.**: When processing Typst source files, some specific variable names, such as bb, cannot be recognized in math mode (they are treated as blank). However, they work fine outside of math mode.

**Pandoc version?**: Pandoc 3.3, the [online demo](https://pandoc.org/try/?params=%7B%22text%22%3A%22%23let+aa+%3D+%24bold%28a%29%24%5Cn%23let+bb+%3D+%24bold%28b%29%24%5Cn%23let+bbb+%3D+%24bold%28b%29%24%5Cn%5Cn%24f%28X%29+%3D+aa%5ET+X+bb%24%5Cn%5Cn%24f%28X%29+%3D+aa%5ET+X+bbb%24%22%2C%22to%22%3A%22markdown%22%2C%22from%22%3A%22typst%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22none%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D). From this link, you can also reproduce the bug.

An minimal example is as the following:

```typst
#let aa = $bold(a)$
#let bb = $bold(b)$
#let bbb = $bold(b)$

$f(X) = aa^T X bb$ #bb

$f(X) = aa^T X bbb$ #bbb
```

And the corresponding markdown (will also meet this bug when choose the other language) result:

```markdown
$f(X) = \mathbf{a}^{T}X$ $\mathbf{b}$

$f(X) = \mathbf{a}^{T}X\mathbf{b}$ $\mathbf{b}$
```

**Comment by jgm** [comment]
Tested with typst.app.  Behavior is a bit surprising!

```
$bb$

$bb(X)$

#let bb=$3$

$bb$

$bb(X)$
```

yields

<img width="161" alt="Screenshot 2024-08-05 at 11 09 12 PM" src="https://github.com/user-attachments/assets/76375e50-7c25-4f04-b815-16303b5baf60">

**Comment by knuesel** [comment]
I think that's expected: bb alone refers to the function (not text), typst shows the function name in monospace. If an argument is given the function is called. But after shadowing the function with the value 3, it's just 3 in both contexts.

**Comment by jgm** [comment]
Even more straightforward repro:
```
#let bb = 3

$bb$
```

should be '3' but is empty.

**Comment by jgm** [comment]
This works okay, so the problem seems specific to math mode:
```
#let emph = 3
#emph 
```

**Comment by jgm** [comment]
I'd like to understand better how this is supposed to work.

For example, `overline` in math mode means math.overline; it doesn't mean what `overline` means outside of math mode.

The way I interpret that is that the implicitly imported `math` module takes precedence over prior bindings.

But apparently if you do `#let bb = 3` outside the scope of the equation, this takes precedence over the implicitly imported `math.bb`.

I'm probably understanding something wrong.  The typst documentation doesn't really clarify this.

**Comment by knuesel** [comment]
It's a bit under documented indeed... From what I understand you have summed it up already: in math mode the math functions shadow the standard functions, but both are shadowed by user-defined bindings defined in the current scope.

(By the way the standard functions will have their own `std` module in the next major release)
