### ISSUE TITLE
Another precedence issue in math parsing

### ISSUE THREAD

**Issue by mathmil** [jgm/typst-hs#55]
Thanks for fixing my last bug report so quickly, this one is quite similar.
typst:
```typst
$
  (b)(c)/(d)
  !(a)/(b)
  \ !(a)/(b)
$
```
typst output:
![typst](https://github.com/user-attachments/assets/0a216178-0ab9-4f74-9080-e740318135b0)

pandoc latex output, identical for newest nightly build and newest release:
```latex
\[\begin{array}{r}
\frac{(b)(c)}{d}\frac{!(a)}{b} \\
!\frac{a}{b}
\end{array}\]
```
Only the first two cases are wrong, but I find it weird that the second and third one differ.

**Comment by jgm** [comment]
Yes, this is definitely quite puzzling:
```
$  
!(a)/b
\
!(a)/b
$
```
I can't currently see why these two cells would be parsed differently.

**Comment by jgm** [comment]
Pandoc yields
```
\frac{!(a)}{b} \\
!\frac{a}{b}
```
And neither is correct. It should be `!\frac{a}{b}`.

**Comment by jgm** [comment]
Related case
```
$
+(a)/(b)
$
```
Here pandoc treats the `+` as part of the numerator, while typst does not.

**Comment by jgm** [comment]
I think what's happening here is that code intended to get the right grouping for
```
f(x)/3
```
is doing the wrong this for
```
!(x)/3
```
and
```
+(x)/3
```

**Comment by jgm** [comment]
It's hard to guess the exact rule typst is using. Note that
```
f(x)/3
```
has f(x) in the numerator, while
```
f_1(x)/3
```
does not have f_1(x) in the numerator.

**Comment by jgm** [comment]
Ah, but
```
f_a(x)/3
```
does have f_a(x) in the numerator.  So I guess the rule has something to do with being followed by a  letter?

**Comment by jgm** [comment]
In my opinion there's a bit too much "magic" in typst's parser.  It makes it hard to predict.

**Comment by jgm** [comment]
Interestingly `f_alpha(x)/3` and `f_"alpha"(x)/3` both pattern with `f_a(x)/3`.
So it's not quite "preceded by a letter."

**Comment by knuesel** [comment]
This is actually an issue with the parsing of subscripts. I think the current behavior was introduced in Typst 0.5 to allow typesetting function calls in subscripts/superscripts without extra parentheses. So `f_a(x)`, `f_alpha(x)` and `f_"alpha"(x)` are all interpreted as a function call in subscript of `f`. Then naturally the fraction `f_a(x)/3` is parsed such that `f_a(x)` is the numerator.

Meanwhile `1(x)` is not treated as a function call, so `f_1(x)/3` is parsed as `f_1 (x)/3`.

I don't think the exact rules are documented anywhere. I guess you can get close enough by treating as a subscript function call anything that looks like a variable name or `"text"` followed by parentheses.

(Many people are unhappy with the current rules and there's been a lot of discussions about a redesign but no decision yet as far as I know.)

**Comment by jgm** [comment]
> Many people are unhappy with the current rules and there's been a lot of discussions about a redesign but no decision yet as far as I know.

If you could link to some of those discussions, it would be useful.

**Comment by knuesel** [comment]
There's some discussion on GitHub in https://github.com/typst/typst/pull/985 and https://github.com/typst/typst/discussions/2086 but most of it was on Discord, in particular:

https://discord.com/channels/1054443721975922748/1176475099940007976 

https://discord.com/channels/1054443721975922748/1176478139757629563/1297121034209722371

https://discord.com/channels/1054443721975922748/1176478139757629563/1249499031873388616

https://discord.com/channels/1054443721975922748/1262525590175617085/1283107875144601715

**Comment by jgm** [comment]
Reopening because we still don't get the original case quite right:
```
document(body: { math.equation(block: true, 
                               body: { math.frac(denom: text(body: [d]), 
                                                 num: { math.lr(body: ({ [(], 
                                                                         text(body: [b]), 
                                                                         [)] })), 
                                                        math.lr(body: ({ [(], 
                                                                         text(body: [c]), 
                                                                         [)] })) }), 
                                       text(body: [!]), 
                                       math.frac(denom: text(body: [b]), 
                                                 num: text(body: [a])), 
                                       linebreak(), 
                                       text(body: [!]), 
                                       math.frac(denom: text(body: [b]), 
                                                 num: text(body: [a])) }, 
                               numbering: none), 
                 parbreak() })
```
We have `\frac{(b)(c)}{d}` but it should be `(b)\frac{c}{d}`.

**Comment by jgm** [comment]
OK I think I've got it now.
