### ISSUE TITLE
Feature request: provide indication on `sys.inputs` that pandoc is running

### ISSUE THREAD

**Issue by ntjess** [jgm/typst-hs#56]
Given the minimal support for `context` and other potential quirks of pandoc interpretation, it might be nice for docs to know whether pandoc is processing them and simplify their layout accordingly.

One way typst supports environment conditions is through [`sys.inputs`](https://typst.app/docs/reference/foundations/sys/).

So ideally, we could write the following code:
```typst
#let template = something-complex-using-context
#if sys.inputs.at("pandoc-version", default: "").match("2\.[0-9]+") != none {
  template = doc => doc
}
```

and it would handle this case (or other version-specific pandoc constraints).

This is unlikely to introduce breaking changes, and providing a version number instead of `true`/`false` allows more backwards compatibility if new features are implemented.

Use case: I use pandoc to create readme's of typst libraries that render their example code into outputs (here's an [example](https://github.com/ntjess/typst-drafting/)). However, this gets difficult when pandoc can't correctly interpret the rendered example code. Ideally, I could tell pandoc within the document to ignore these blocks when running.

Packages could also use this to insert phrases like `"this document only compiles on pandoc 3.4.x+."` or to panic with more informative error messages.

**Comment by jgm** [comment]
That's a nice idea.  But since the typst interpreter is from the `typst` package, maybe it makes more sense to set `sys.inputs.at("typst-hs version")`?  Indeed, the typst interpreter doesn't know the pandoc version.

**Comment by ntjess** [comment]
`typst-hs-version` makes sense to me. Would there be any benefit to _also_ including the pandoc version?

**Comment by jgm** [comment]
I don't see how to include the pandoc version.  The interpretation of typst code is done by typst-hs, and it doesn't know the pandoc version.
